// Generated by scripts/generate-languages.mjs; edit src/lib/languages.json.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum TargetLanguage {
    #[serde(rename = "af")]
    Af,
    #[serde(rename = "ak")]
    Ak,
    #[serde(rename = "sq")]
    Sq,
    #[serde(rename = "am")]
    Am,
    #[serde(rename = "ar")]
    Ar,
    #[serde(rename = "hy")]
    Hy,
    #[serde(rename = "az")]
    Az,
    #[serde(rename = "eu")]
    Eu,
    #[serde(rename = "be")]
    Be,
    #[serde(rename = "bn")]
    Bn,
    #[serde(rename = "bg")]
    Bg,
    #[serde(rename = "my")]
    My,
    #[serde(rename = "ca")]
    Ca,
    #[serde(rename = "zh-Hans")]
    ZhHans,
    #[serde(rename = "zh-Hant")]
    ZhHant,
    #[serde(rename = "hr")]
    Hr,
    #[serde(rename = "cs")]
    Cs,
    #[serde(rename = "da")]
    Da,
    #[serde(rename = "nl")]
    Nl,
    #[serde(rename = "en")]
    En,
    #[serde(rename = "et")]
    Et,
    #[serde(rename = "fil")]
    Fil,
    #[serde(rename = "fi")]
    Fi,
    #[serde(rename = "fr")]
    Fr,
    #[serde(rename = "gl")]
    Gl,
    #[serde(rename = "ka")]
    Ka,
    #[serde(rename = "de")]
    De,
    #[serde(rename = "el")]
    El,
    #[serde(rename = "gu")]
    Gu,
    #[serde(rename = "ha")]
    Ha,
    #[serde(rename = "he")]
    He,
    #[serde(rename = "hi")]
    Hi,
    #[serde(rename = "hu")]
    Hu,
    #[serde(rename = "is")]
    Is,
    #[serde(rename = "id")]
    Id,
    #[serde(rename = "it")]
    It,
    #[serde(rename = "ja")]
    Ja,
    #[serde(rename = "jv")]
    Jv,
    #[serde(rename = "kn")]
    Kn,
    #[serde(rename = "kk")]
    Kk,
    #[serde(rename = "km")]
    Km,
    #[serde(rename = "rw")]
    Rw,
    #[serde(rename = "ko")]
    Ko,
    #[serde(rename = "lo")]
    Lo,
    #[serde(rename = "lv")]
    Lv,
    #[serde(rename = "lt")]
    Lt,
    #[serde(rename = "mk")]
    Mk,
    #[serde(rename = "ms")]
    Ms,
    #[serde(rename = "ml")]
    Ml,
    #[serde(rename = "mr")]
    Mr,
    #[serde(rename = "mn")]
    Mn,
    #[serde(rename = "ne")]
    Ne,
    #[serde(rename = "no")]
    No,
    #[serde(rename = "fa")]
    Fa,
    #[serde(rename = "pl")]
    Pl,
    #[serde(rename = "pt-BR")]
    PtBr,
    #[serde(rename = "pt-PT")]
    PtPt,
    #[serde(rename = "pa")]
    Pa,
    #[serde(rename = "ro")]
    Ro,
    #[serde(rename = "ru")]
    Ru,
    #[serde(rename = "sr")]
    Sr,
    #[serde(rename = "sd")]
    Sd,
    #[serde(rename = "si")]
    Si,
    #[serde(rename = "sk")]
    Sk,
    #[serde(rename = "sl")]
    Sl,
    #[serde(rename = "es")]
    Es,
    #[serde(rename = "su")]
    Su,
    #[serde(rename = "sw")]
    Sw,
    #[serde(rename = "sv")]
    Sv,
    #[serde(rename = "ta")]
    Ta,
    #[serde(rename = "te")]
    Te,
    #[serde(rename = "th")]
    Th,
    #[serde(rename = "tr")]
    Tr,
    #[serde(rename = "uk")]
    Uk,
    #[serde(rename = "ur")]
    Ur,
    #[serde(rename = "uz")]
    Uz,
    #[serde(rename = "vi")]
    Vi,
    #[serde(rename = "zu")]
    Zu,
    #[serde(rename = "pt")]
    Pt,
    #[serde(rename = "zh")]
    Zh,
}

impl TargetLanguage {
    pub fn bcp47(self) -> &'static str {
        match self {
            Self::Af => "af",
            Self::Ak => "ak",
            Self::Sq => "sq",
            Self::Am => "am",
            Self::Ar => "ar",
            Self::Hy => "hy",
            Self::Az => "az",
            Self::Eu => "eu",
            Self::Be => "be",
            Self::Bn => "bn",
            Self::Bg => "bg",
            Self::My => "my",
            Self::Ca => "ca",
            Self::ZhHans => "zh-Hans",
            Self::ZhHant => "zh-Hant",
            Self::Hr => "hr",
            Self::Cs => "cs",
            Self::Da => "da",
            Self::Nl => "nl",
            Self::En => "en",
            Self::Et => "et",
            Self::Fil => "fil",
            Self::Fi => "fi",
            Self::Fr => "fr",
            Self::Gl => "gl",
            Self::Ka => "ka",
            Self::De => "de",
            Self::El => "el",
            Self::Gu => "gu",
            Self::Ha => "ha",
            Self::He => "he",
            Self::Hi => "hi",
            Self::Hu => "hu",
            Self::Is => "is",
            Self::Id => "id",
            Self::It => "it",
            Self::Ja => "ja",
            Self::Jv => "jv",
            Self::Kn => "kn",
            Self::Kk => "kk",
            Self::Km => "km",
            Self::Rw => "rw",
            Self::Ko => "ko",
            Self::Lo => "lo",
            Self::Lv => "lv",
            Self::Lt => "lt",
            Self::Mk => "mk",
            Self::Ms => "ms",
            Self::Ml => "ml",
            Self::Mr => "mr",
            Self::Mn => "mn",
            Self::Ne => "ne",
            Self::No => "no",
            Self::Fa => "fa",
            Self::Pl => "pl",
            Self::PtBr => "pt-BR",
            Self::PtPt => "pt-PT",
            Self::Pa => "pa",
            Self::Ro => "ro",
            Self::Ru => "ru",
            Self::Sr => "sr",
            Self::Sd => "sd",
            Self::Si => "si",
            Self::Sk => "sk",
            Self::Sl => "sl",
            Self::Es => "es",
            Self::Su => "su",
            Self::Sw => "sw",
            Self::Sv => "sv",
            Self::Ta => "ta",
            Self::Te => "te",
            Self::Th => "th",
            Self::Tr => "tr",
            Self::Uk => "uk",
            Self::Ur => "ur",
            Self::Uz => "uz",
            Self::Vi => "vi",
            Self::Zu => "zu",
            Self::Pt => "pt",
            Self::Zh => "zh",
        }
    }

    pub fn supported_by(self, provider: Provider) -> bool {
        match provider {
            Provider::Gemini => matches!(
                self,
                Self::Af
                    | Self::Ak
                    | Self::Sq
                    | Self::Am
                    | Self::Ar
                    | Self::Hy
                    | Self::Az
                    | Self::Eu
                    | Self::Be
                    | Self::Bn
                    | Self::Bg
                    | Self::My
                    | Self::Ca
                    | Self::ZhHans
                    | Self::ZhHant
                    | Self::Hr
                    | Self::Cs
                    | Self::Da
                    | Self::Nl
                    | Self::En
                    | Self::Et
                    | Self::Fil
                    | Self::Fi
                    | Self::Fr
                    | Self::Gl
                    | Self::Ka
                    | Self::De
                    | Self::El
                    | Self::Gu
                    | Self::Ha
                    | Self::He
                    | Self::Hi
                    | Self::Hu
                    | Self::Is
                    | Self::Id
                    | Self::It
                    | Self::Ja
                    | Self::Jv
                    | Self::Kn
                    | Self::Kk
                    | Self::Km
                    | Self::Rw
                    | Self::Ko
                    | Self::Lo
                    | Self::Lv
                    | Self::Lt
                    | Self::Mk
                    | Self::Ms
                    | Self::Ml
                    | Self::Mr
                    | Self::Mn
                    | Self::Ne
                    | Self::No
                    | Self::Fa
                    | Self::Pl
                    | Self::PtBr
                    | Self::PtPt
                    | Self::Pa
                    | Self::Ro
                    | Self::Ru
                    | Self::Sr
                    | Self::Sd
                    | Self::Si
                    | Self::Sk
                    | Self::Sl
                    | Self::Es
                    | Self::Su
                    | Self::Sw
                    | Self::Sv
                    | Self::Ta
                    | Self::Te
                    | Self::Th
                    | Self::Tr
                    | Self::Uk
                    | Self::Ur
                    | Self::Uz
                    | Self::Vi
                    | Self::Zu
            ),
            Provider::OpenAi => matches!(
                self,
                Self::En
                    | Self::Fr
                    | Self::De
                    | Self::Hi
                    | Self::Id
                    | Self::It
                    | Self::Ja
                    | Self::Ko
                    | Self::Ru
                    | Self::Es
                    | Self::Vi
                    | Self::Pt
                    | Self::Zh
            ),
            Provider::OnDevice => matches!(
                self,
                Self::En
                    | Self::Fr
            ),
            Provider::Mistral | Provider::GeminiTranscribe => true,
        }
    }
}
