//! Rehearsal mode: a bundled speech recording played through the live capture pipeline.
//!
//! Rehearsal replaces the capture *device*, not the pipeline behind it. The fixture is fed to
//! the same [`CaptureState`] the microphone and loopback paths use, so it is resampled to the
//! provider's rate, metered on the same level events, and cut into the same ~100 ms chunks —
//! and everything downstream (the selected engine, captions, transcript, overlay) is the live
//! code path. That is the whole point: a certification tester on a clean virtual machine, or
//! an operator setting up an empty hall, can exercise the entire app with no microphone and
//! no sound in the room. See gate 2 in `docs/microsoft-store.md`.
//!
//! The recordings themselves are committed under `src-tauri/resources/fixtures/` and
//! regenerated by `scripts/generate-rehearsal-fixtures.ps1`.

use std::path::{Path, PathBuf};
use std::time::Duration;

use anyhow::{anyhow, Result};
use tauri::{AppHandle, Manager};
use tokio::sync::mpsc::Sender;
use tokio_util::sync::CancellationToken;

use super::capture::CaptureState;
use super::{chunk_samples, AudioChunk, CHUNK_MS};
use crate::types::{AudioLevel, Origin, TargetLanguage};

/// Directory the fixtures are bundled into, relative to the app's resource directory —
/// `bundle.resources` in `tauri.conf.json` maps `resources/fixtures/*` here. Resolved through
/// the same static-resource mechanism used by other bundled app assets.
const FIXTURE_DIR: &str = "fixtures";

/// The rate the fixtures are generated at. The loader rejects anything else rather than
/// guessing: a wrong-format fixture is a packaging mistake, not something to accommodate.
const FIXTURE_RATE: u32 = 16_000;

/// Uncompressed PCM, the only `fmt ` tag a fixture may carry.
const WAVE_FORMAT_PCM: u16 = 1;

/// Silence inserted between repeats, so a looping fixture sounds like a pause between two
/// talks rather than a splice, and the engine closes the turn before the next one opens.
const REPEAT_GAP_MS: usize = 2_000;

/// Silent samples between repeats, at the fixture's rate.
fn gap_samples() -> usize {
    FIXTURE_RATE as usize * REPEAT_GAP_MS / 1000
}

/// Where the fixture for `language` lives in the installed app.
fn fixture_path(app: &AppHandle, language: TargetLanguage) -> Result<PathBuf> {
    let file = match language {
        TargetLanguage::En => "rehearsal-en.wav",
        TargetLanguage::Fr => "rehearsal-fr.wav",
    };
    app.path()
        .resolve(
            format!("{FIXTURE_DIR}/{file}"),
            tauri::path::BaseDirectory::Resource,
        )
        .map_err(|error| anyhow!("could not locate the app resource directory: {error}"))
}

/// Read and validate one fixture. Every error names the path: when this fails, what the
/// operator needs to know is which file the build is missing or mangled.
fn load_fixture(path: &Path) -> Result<Vec<f32>> {
    let bytes = std::fs::read(path).map_err(|error| {
        anyhow!(
            "could not read the rehearsal fixture {}: {error}",
            path.display()
        )
    })?;
    parse_fixture_wav(&bytes).map_err(|error| {
        anyhow!(
            "the rehearsal fixture {} is unusable: {error}",
            path.display()
        )
    })
}

/// Read a little-endian `u16` at `offset`, or `None` if the field runs past the end.
fn u16_at(bytes: &[u8], offset: usize) -> Option<u16> {
    let field = bytes.get(offset..offset + 2)?;
    Some(u16::from_le_bytes([field[0], field[1]]))
}

/// Read a little-endian `u32` at `offset`, or `None` if the field runs past the end.
fn u32_at(bytes: &[u8], offset: usize) -> Option<u32> {
    let field = bytes.get(offset..offset + 4)?;
    Some(u32::from_le_bytes([field[0], field[1], field[2], field[3]]))
}

/// Decode a RIFF/WAVE file that must be 16 kHz mono signed 16-bit PCM, returning its samples
/// in [-1, 1].
///
/// Hand-rolled deliberately: this reads one asset we generate ourselves, so the job is to
/// validate *our own* format and refuse everything else, not to decode arbitrary audio — which
/// would mean a decoder dependency for a 650 KB file. The chunk list is walked rather than
/// assuming the canonical 44-byte header, because the synthesizer writes an 18-byte `fmt `
/// chunk (`WAVEFORMATEX` with a zero `cbSize`).
fn parse_fixture_wav(bytes: &[u8]) -> Result<Vec<f32>> {
    anyhow::ensure!(
        bytes.len() >= 12,
        "the file is too short to be a RIFF container"
    );
    anyhow::ensure!(&bytes[0..4] == b"RIFF", "the RIFF tag is missing");
    anyhow::ensure!(&bytes[8..12] == b"WAVE", "the RIFF container is not a WAVE");

    let mut described = false;
    let mut data: Option<&[u8]> = None;
    let mut offset = 12;

    // Each iteration advances by at least the 8-byte chunk header, so this always terminates.
    while offset + 8 <= bytes.len() {
        let id = &bytes[offset..offset + 4];
        let size = u32_at(bytes, offset + 4)
            .ok_or_else(|| anyhow!("a chunk header is cut short"))? as usize;
        let body = offset + 8;
        let end = body
            .checked_add(size)
            .filter(|end| *end <= bytes.len())
            .ok_or_else(|| anyhow!("a {size}-byte chunk runs past the end of the file"))?;

        if id == b"fmt " {
            anyhow::ensure!(
                size >= 16,
                "the fmt chunk is {size} bytes, expected 16 or more"
            );
            // Every field below sits inside the 16 bytes just checked for, so the defaults
            // are unreachable — they are how this stays free of `unwrap`, not a fallback.
            let fmt = &bytes[body..end];
            let tag = u16_at(fmt, 0).unwrap_or_default();
            let channels = u16_at(fmt, 2).unwrap_or_default();
            let rate = u32_at(fmt, 4).unwrap_or_default();
            let bits = u16_at(fmt, 14).unwrap_or_default();
            anyhow::ensure!(
                tag == WAVE_FORMAT_PCM,
                "format tag {tag}, expected uncompressed PCM ({WAVE_FORMAT_PCM})"
            );
            anyhow::ensure!(channels == 1, "{channels} channels, expected mono");
            anyhow::ensure!(
                rate == FIXTURE_RATE,
                "{rate} Hz, expected {FIXTURE_RATE} Hz"
            );
            anyhow::ensure!(bits == 16, "{bits}-bit samples, expected 16-bit");
            described = true;
        } else if id == b"data" {
            data = Some(&bytes[body..end]);
        }

        // RIFF chunks are word-aligned: an odd size is followed by a pad byte.
        offset = end + (size & 1);
    }

    anyhow::ensure!(described, "there is no fmt chunk");
    let data = data.ok_or_else(|| anyhow!("there is no data chunk"))?;
    anyhow::ensure!(!data.is_empty(), "the data chunk carries no audio");
    anyhow::ensure!(
        data.len() % 2 == 0,
        "the data chunk is {} bytes, not a whole number of 16-bit frames",
        data.len()
    );

    Ok(data
        .as_chunks::<2>()
        .0
        .iter()
        .map(|frame| i16::from_le_bytes(*frame) as f32 / 32768.0)
        .collect())
}

/// One fixture on repeat: the whole recording, then a short silence, for as long as the
/// session runs. Pure and frame-based, so the looping is unit-tested without a clock.
struct FixtureLoop {
    samples: Vec<f32>,
    /// Silent samples appended after each repeat.
    gap: usize,
    position: usize,
}

impl FixtureLoop {
    fn new(samples: Vec<f32>, gap: usize) -> Self {
        Self {
            samples,
            gap,
            position: 0,
        }
    }

    /// Samples in one repeat: speech plus gap.
    fn period(&self) -> usize {
        self.samples.len() + self.gap
    }

    /// Replace `out` with the next `frame` samples of the loop, zero-filling the gap.
    fn next_frame(&mut self, frame: usize, out: &mut Vec<f32>) {
        out.clear();
        if self.period() == 0 {
            // An empty fixture is rejected at load time; keep the fill finite regardless.
            out.resize(frame, 0.0);
            return;
        }
        while out.len() < frame {
            let wanted = frame - out.len();
            if self.position < self.samples.len() {
                let take = wanted.min(self.samples.len() - self.position);
                out.extend_from_slice(&self.samples[self.position..self.position + take]);
                self.position += take;
            } else {
                let take = wanted.min(self.period() - self.position);
                out.resize(out.len() + take, 0.0);
                self.position += take;
            }
            if self.position >= self.period() {
                self.position = 0;
            }
        }
    }
}

/// Play the bundled fixture for `language` into the capture pipeline until `cancel` fires.
///
/// Mirrors what a real capture does for [`Origin::System`] — same channels, same chunk shape,
/// same level events — so the session cannot tell the difference. Only the sample source does.
pub async fn run_rehearsal(
    app: &AppHandle,
    language: TargetLanguage,
    target_rate: u32,
    level_tx: Sender<AudioLevel>,
    chunk_tx: Sender<AudioChunk>,
    cancel: CancellationToken,
) -> Result<()> {
    let path = fixture_path(app, language)?;

    // Reading and decoding the fixture is filesystem work; keep it off the async runtime, as
    // a recognizer does while it initializes.
    let load_path = path.clone();
    let samples = tauri::async_runtime::spawn_blocking(move || load_fixture(&load_path))
        .await
        .map_err(|error| anyhow!("the rehearsal fixture load task failed: {error}"))??;

    tracing::info!(
        path = %path.display(),
        seconds = samples.len() as f64 / FIXTURE_RATE as f64,
        "starting rehearsal fixture playback"
    );

    // `CaptureState` resamples the fixture to the provider's rate and does the metering and
    // chunking, exactly as it does for a device.
    let mut state = CaptureState::new(
        Origin::System,
        FIXTURE_RATE,
        target_rate,
        level_tx,
        chunk_tx,
    );
    let mut playback = FixtureLoop::new(samples, gap_samples());
    let frame = chunk_samples(FIXTURE_RATE);
    let mut buffer = Vec::with_capacity(frame);

    // Real-time pacing: one ~100 ms frame per tick, so captions arrive at the cadence of a
    // live talk rather than as a burst no realtime API would accept.
    let mut ticker = tokio::time::interval(Duration::from_millis(CHUNK_MS as u64));
    ticker.set_missed_tick_behavior(tokio::time::MissedTickBehavior::Delay);

    loop {
        tokio::select! {
            _ = cancel.cancelled() => break,
            _ = ticker.tick() => {
                playback.next_frame(frame, &mut buffer);
                state.push_samples(&buffer, 1);
            }
        }
    }

    tracing::info!("rehearsal fixture playback stopped");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Build a minimal RIFF/WAVE buffer, including the 18-byte `fmt ` chunk the synthesizer
    /// writes, so the parser is tested against the shape it actually meets.
    fn wav(channels: u16, rate: u32, bits: u16, samples: &[i16]) -> Vec<u8> {
        let data: Vec<u8> = samples.iter().flat_map(|s| s.to_le_bytes()).collect();

        let mut fmt = Vec::new();
        fmt.extend_from_slice(&WAVE_FORMAT_PCM.to_le_bytes());
        fmt.extend_from_slice(&channels.to_le_bytes());
        fmt.extend_from_slice(&rate.to_le_bytes());
        fmt.extend_from_slice(&(rate * channels as u32 * bits as u32 / 8).to_le_bytes());
        fmt.extend_from_slice(&(channels * bits / 8).to_le_bytes());
        fmt.extend_from_slice(&bits.to_le_bytes());
        fmt.extend_from_slice(&0u16.to_le_bytes());

        let mut out = Vec::new();
        out.extend_from_slice(b"RIFF");
        out.extend_from_slice(&((4 + 8 + fmt.len() + 8 + data.len()) as u32).to_le_bytes());
        out.extend_from_slice(b"WAVE");
        out.extend_from_slice(b"fmt ");
        out.extend_from_slice(&(fmt.len() as u32).to_le_bytes());
        out.extend_from_slice(&fmt);
        out.extend_from_slice(b"data");
        out.extend_from_slice(&(data.len() as u32).to_le_bytes());
        out.extend_from_slice(&data);
        out
    }

    #[test]
    fn parses_the_format_the_generator_writes() {
        let bytes = wav(1, FIXTURE_RATE, 16, &[0, 16_384, -16_384, i16::MIN]);
        let samples = parse_fixture_wav(&bytes).expect("a well-formed fixture");
        assert_eq!(samples, vec![0.0, 0.5, -0.5, -1.0]);
    }

    #[test]
    fn rejects_a_truncated_file() {
        let bytes = wav(1, FIXTURE_RATE, 16, &[1, 2, 3, 4]);
        // Cut inside the data chunk: its header still promises eight bytes of samples.
        assert!(parse_fixture_wav(&bytes[..bytes.len() - 3]).is_err());
        // Cut before the format is described at all.
        assert!(parse_fixture_wav(&bytes[..8]).is_err());
        assert!(parse_fixture_wav(&[]).is_err());
    }

    #[test]
    fn rejects_anything_that_is_not_16_khz_mono_16_bit_pcm() {
        assert!(parse_fixture_wav(&wav(2, FIXTURE_RATE, 16, &[0, 0])).is_err());
        assert!(parse_fixture_wav(&wav(1, 44_100, 16, &[0, 0])).is_err());
        assert!(parse_fixture_wav(&wav(1, FIXTURE_RATE, 8, &[0, 0])).is_err());
        // Silence is a valid signal, but an empty recording is a broken build.
        assert!(parse_fixture_wav(&wav(1, FIXTURE_RATE, 16, &[])).is_err());

        let mut not_riff = wav(1, FIXTURE_RATE, 16, &[0, 0]);
        not_riff[0] = b'X';
        assert!(parse_fixture_wav(&not_riff).is_err());
    }

    #[test]
    fn playback_loops_the_fixture_with_a_silent_gap() {
        let mut playback = FixtureLoop::new(vec![0.5; 3], 2);
        let mut out = Vec::new();

        playback.next_frame(2, &mut out);
        assert_eq!(out, vec![0.5, 0.5]);
        // Straddles the end of the speech: one sample of audio, then the gap.
        playback.next_frame(3, &mut out);
        assert_eq!(out, vec![0.5, 0.0, 0.0]);
        // And wraps into the next repeat.
        playback.next_frame(3, &mut out);
        assert_eq!(out, vec![0.5, 0.5, 0.5]);
    }

    #[test]
    fn a_frame_longer_than_the_loop_is_filled_exactly() {
        let mut playback = FixtureLoop::new(vec![1.0; 2], 1);
        let mut out = Vec::new();
        playback.next_frame(7, &mut out);
        assert_eq!(out, vec![1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0]);
    }

    #[test]
    fn an_empty_loop_produces_silence_rather_than_spinning() {
        let mut playback = FixtureLoop::new(Vec::new(), 0);
        let mut out = Vec::new();
        playback.next_frame(4, &mut out);
        assert_eq!(out, vec![0.0; 4]);
    }

    #[test]
    fn pacing_matches_the_capture_pipeline() {
        // One tick feeds exactly one ~100 ms chunk at the fixture's rate.
        assert_eq!(chunk_samples(FIXTURE_RATE), 1_600);
        assert_eq!(gap_samples(), 32_000);
    }
}
